myList=list(map(int,input().split(",")))
print(myList)
n=int(input("enter the value you want to delete"))
x=int(input("input the value you want to insert"))
z=int(input("enter the position where you want to inster the value"))
index=myList.index(n)
myList.pop(index)
myList.insert(z-1,x)
print(myList)