mylist=list(map(int, input().split(" ")))
print(mylist)
x=int(input("enter value to be inserted"))
x1=int(input("enter position to insert the value given"))
mylist.insert(x1-1,x)
print(mylist)
d=int(input("enter the value to be deleted"))
index=mylist.index(d)
mylist.pop(index)
print(mylist)
i=int(input("enter the value to be inserted at the last"))
mylist.append(i)
print(mylist)
k=int(input("enter 1 for ascending 2 for descending"))
if(k==1):
    mylist.sort()
    print(mylist)
else:
    mylist.sort(reverse=True)
    print(mylist)